### ISSUE TITLE
Hello.g4 : Edit grammar for member variables and abstract methods of interface

### ISSUE THREAD

**Issue by gayeon1025** [Ko-language/Ko-language#14]
According to current grammar, interface doesn't have member variables and the abstract method of interface cannot be expressed.

Below is the example of abstract method of interface intended
```
틀 언어 {
    소통하다();
} 
```
But now, the method of interface always accompany compound.

**Comment by rlaehgns5399** [comment]
Let me solve this issue 👍

**Comment by gayeon1025** [comment]
OK 👍  @rlaehgns5399
