### ISSUE TITLE
Hello.g4 : How do we distinguish the scope of local variables?

### ISSUE THREAD

**Issue by gayeon1025** [Ko-language/Ko-language#15]
```
# [클래스] {
    |눈<-2, 귀<-2, 입<-1, 임시변수<-3|

    메소드 () {
        임시변수 <- 5
        임시변수 내보내기
    }
}
```

If I want for 임시변수 in the method to be owned by 메소드, 
but Ko-language cannot distinguish the ownership of variables.

Then how should we solve this problem? 
I guess we have to add a grammar.

**Comment by woonhyeong** [comment]
In a class, you can't declare method variable having the same name with variable field.
why don't you make 'global' keyword instead, like python?

**Comment by gayeon1025** [comment]
Okay. I will register new issue.
